#!/usr/bin/env sh
. "${0%/*}/h"

echo 'Commit test init...'

# Running Prettier standards
npm run format ||
(
    echo 'Write Prettier errors found.';
    false;
)

# Running Lint standards
npm run lint ||
(
    echo 'Write Prettier errors found.';
    false;
)

# Running Unit test
npm run test ||
(
    echo 'Write Prettier errors found.';
    false;
)

# Running E2E test
npm run cypress:run ||
(
    echo 'Write Prettier errors found.';
    false;
)